.gitignore, Makefile, cmd/cortex/cvm.go, cmd/tracker/main.go, cvm.sh, cvm_gpu.sh, params/trackers.go, start.sh, start_gpu.sh, torrentfs/config.go, torrentfs/monitor.go, torrentfs/storage.go, torrentfs/torrentClient.go, tracker.sh
=> [tracker] developing .... decentralization p2p node tracker ips seeding

torrentfs/client.go, torrentfs/files.go, torrentfs/monitor.go
We add the whitelist of file for more stable blockchain synchronize
=> fs/client,files,monitor | whitelist for boosting

common/big.go
Big256 should be 256 rather than 0xff
=> fix the Big256 bug

go.mod, go.sum, vendor/github.com/CortexFoundation/torrentfs/blockchain.go, vendor/github.com/CortexFoundation/torrentfs/files.go, vendor/github.com/CortexFoundation/torrentfs/handler.go, vendor/github.com/CortexFoundation/torrentfs/torrent.go, vendor/modules.txt
https://github.com/CortexFoundation/torrentfs
=> Tiny fix from file storage of cortex

consensus/cuckoo/consensus.go, core/block_validator.go, core/blocks.go
1. Move dictionary FixHashes from core package into cuckoo
2. Move function CheckGasLimit from core package into cuckoo
3. Fix some name in designed errors
=> Move the import from core to cuckoo

miner/miner.go
https://github.com/CortexFoundation/CortexTheseus/pull/640
https://github.com/ethereum/go-ethereum/pull/21286
https://github.com/ethereum/go-ethereum/pull/21287
=> miner subscribe event split

common/lru/lru_test.go, console/console.go, go.mod, go.sum, internal/ctxcapi/api.go, miner/miner.go, vendor/github.com/CortexFoundation/torrentfs/.gitignore, vendor/github.com/CortexFoundation/torrentfs/Makefile, vendor/github.com/CortexFoundation/torrentfs/README.md, vendor/github.com/CortexFoundation/torrentfs/api.go, vendor/github.com/CortexFoundation/torrentfs/doc.go, vendor/github.com/CortexFoundation/torrentfs/fs.go, vendor/github.com/CortexFoundation/torrentfs/go.mod, vendor/github.com/CortexFoundation/torrentfs/handler.go, vendor/github.com/CortexFoundation/torrentfs/params/chain.go, vendor/github.com/CortexFoundation/torrentfs/params/tracker.go, vendor/github.com/CortexFoundation/torrentfs/peer.go, vendor/modules.txt
=> common/lru: unit-test(not complete)

core/blockchain_test.go, core/cvm.go, core/genesis.go, core/state/statedb.go, core/vm/contracts.go, core/vm/contracts_test.go, core/vm/cvm.go, core/vm/gen_structlog.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/logger.go, core/vm/logger_json.go, core/vm/logger_test.go, core/vm/runtime/runtime.go, core/vm/runtime/runtime_test.go, core/vm/stack.go, ctxc/tracers/tracer.go, ctxc/tracers/tracer_test.go, trie/committer.go, trie/secure_trie.go
New changes from ethereum for vm, need to review the merge and run more tesing
=> core/vm: less allocations for various call variants

client/ctxc_client.go, core/state_transition.go, core/types/gen_log_json.go, core/types/log.go, go.mod, go.sum, inference/synapse/local_infer.go, params/network_params.go, vendor/github.com/CortexFoundation/torrentfs/fs.go, vendor/github.com/CortexFoundation/torrentfs/handler.go, vendor/github.com/CortexFoundation/torrentfs/sync.go, vendor/github.com/CortexFoundation/torrentfs/types/common.go, vendor/modules.txt
1. Download operation when cur > 0
2. Add timeout for fs download
=> File storage control opt

core/vm/cvm.go, core/vm/instructions.go
1. convert some name from "in" to "cvm" to keep unity
2. convert "<=" into "==" for modelShape which is of uint64 type #722
=> fix some details 

core/state/statedb.go
* core/state: maintain one more diff layer
* core/state: address comment
=> core/state: maintain one more diff layer (#21730)

cmd/cortex/main.go, cmd/cortex/usage.go, cmd/utils/flags.go
White list for special block hash
=> Add whitelist flag

consensus/cuckoo/consensus.go, core/headerchain.go, core/rawdb/freezer_table.go
https://github.com/holiman/headerimport/blob/main/README.md#1m-blocks-on-21471
=> Header check

consensus/cuckoo/consensus.go, core/headerchain.go, core/rawdb/freezer_table.go
Reverts CortexFoundation/CortexTheseus#868
=> Revert "Header check"

cmd/utils/flags.go, internal/ctxcapi/api.go
* cmd/utils: fix exclusive check for archive node
* cmd/utils: set the txlookuplimit to 0
=> cmd/utils: fix txlookuplimit for archive node

cmd/cortex/main.go, cmd/cortex/usage.go, cmd/utils/flags.go, core/blockchain.go, ctxc/backend.go, ctxc/config.go, ctxc/gen_config.go, params/security.go
```
--viper                    Sync block with 180s local sprout time
```
```
./cortex --viper
```
=> viper boot mode

metrics/cpu_syscall.go
Fixes #11113
Co-authored-by: rene <41963722+renaynay@users.noreply.github.com>
=> metrics: use golang.org/x/sys/unix to support Solaris

consensus/cuckoo/consensus.go, consensus/cuckoo/consensus_test.go, core/vm/contracts.go, core/vm/cvm.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/jump_table.go, miner/worker.go, params/config.go, params/protocol_params.go
1. ethereum return data corruption bug fix
2. low diff adjust fix
Neo block is pending
=> Neo version 4 cortex full node

rpc/client.go
* rpc: set scheme for ws and ipc conns to the server
* rpc: review fixes
* rpc: bugfix
* rpc: empty default scheme
=> rpc: set scheme for ws and ipc conns to the server 

.github/workflows/codeql-analysis.yml
Reverts CortexFoundation/CortexTheseus#1060
=> Revert "cql remove"

rpc/client.go
This avoids quadratic time complexity in the lookup of the batch element
corresponding to an RPC response. Unfortunately, the new approach
requires additional memory for the mapping from ID to index.
=> rpc: linear time batch response matching

ctxc/api_backend.go, go.mod, go.sum, internal/ctxcapi/api.go, internal/ctxcapi/backend.go, internal/web3ext/web3ext.go, vendor/github.com/CortexFoundation/inference/synapse/local_infer.go, vendor/github.com/CortexFoundation/inference/synapse/synapse.go, vendor/github.com/CortexFoundation/torrentfs/fs.go, vendor/github.com/CortexFoundation/torrentfs/handler.go, vendor/github.com/CortexFoundation/torrentfs/interfaces.go, vendor/modules.txt
Add New Features:
1. PauseLocalSeed
2. ResumeLocalSeed
3. ListAllTorrents
=> Fs module v0.0.2

consensus/clique/api.go
* clique: fix block number unmarshal
* clique: rename
=> consensus/clique: fix block number unmarshal

core/vm/errors.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/jump_table.go
including NEO block version check
=> core/vm: simplify error handling in interpreter loop

go.mod, go.sum, vendor/github.com/CortexFoundation/torrentfs/handler.go, vendor/github.com/anacrolix/torrent/storage/default-dir-piece-completion-boltdb.go, vendor/github.com/anacrolix/torrent/storage/default-dir-piece-completion-other.go, vendor/github.com/anacrolix/torrent/storage/default-dir-piece-completion-sqlite.go, vendor/github.com/anacrolix/torrent/storage/sqlite-piece-completion.go, vendor/github.com/anacrolix/torrent/torrent.go, vendor/github.com/anacrolix/torrent/webseed-peer.go, vendor/github.com/anacrolix/torrent/webseed/client.go, vendor/modules.txt
=> fs lazy for developer

core/vm/eips.go, core/vm/opcodes.go
* core/vm: Implement PUSH0
* Move PUSH0 to enable3855
* Add method doc
=> core/vm: implement EIP-3855: PUSH0 instruction

core/vm/memory.go
* core/vm: remove unnecessary memset for Memory.Set32
* core/vm: optimize Memory.Set32
=> core/vm: optimize Memory.Set32

core/vm/analysis.go
core/vm: optimize PUSH opcode discrimination
=> core/vm: optimize jumpdest analysis

p2p/discover/lookup.go, p2p/discover/v4_udp.go, p2p/discover/v5_udp.go, p2p/discover/v5wire/encoding.go, p2p/dnsdisc/client.go, p2p/enr/entries.go, p2p/peer.go, p2p/peer_error.go, p2p/simulations/http.go
=> p2p: use errors.Is for error comparison 

common/format.go
* common: improve pretty duration regex
* common: improve pretty duration regex
=> common: improve pretty duration regex

core/tx_journal.go, go.mod
* core: reduce system call about `os`
* avoid deprecated method
=> core: make tx journal check and open atomic 

p2p/enode/iter.go
=> p2p/enode: implement per-source timeout in FairMix (#25962)

common/types.go, common/types_test.go
Fix the json marshaller of MixedcaseAddress
=> common: fix json marshaller MixedcaseAddress

internal/build/util.go, internal/debug/trace.go, internal/web3ext/web3ext.go
* ✏️ Fix typos
* ⏪️ Revert changes
* Update internal/web3ext/web3ext.go
---------
=> graphql, internal: fix typos in comments

rpc/client.go, rpc/server.go, signer/core/stdioui.go
=> rpc: use atomic types

core/state/statedb.go
* core/state : fix map size avoid resizing
* core/state : fixed size
=> core/state: initialize maps with known size

miner/worker.go
* miner : initialize maps with known size
* miner:some reverts
=> miner: initialize maps with capacity

event/event.go
event: initialize maps with known size
=> event: initialize maps with known size

core/state/journal.go, core/state/statedb.go, core/state/statedb_test.go
* core/state: remove cached snap data if reset occurs
* core/state: address comment from peter
* core/state: skip revert in case data is nil
=> core/state: clear out cached state data when reset occurs

common/types.go, consensus/clique/snapshot.go, consensus/clique/snapshot_test.go
Also adds Address.Less for sorting use in other packages.
---------
=> consensus/clique: use slices package for sorting

core/blockchain.go
This error will never happen, but if it ever does happen, we will at least see it.
=> core: log message if DeriveFields returns error

core/blockchain.go
Currently, we trigger the logic to (un)index transactions when the node receives a new block. However, in some cases the node may not receive new blocks (eg, when the Geth node is configured without peer discovery, or when it acts as an RPC node for historical-only data).
In these situations, the Geth node user may not have previously configured txlookuplimit (i.e. the default of around one year), but later realizes they need to index all historical blocks. However, adding txlookuplimit=0 and restarting geth has no effect. This change makes it check for required indexing work once, on startup, to fix the issue.
=> core: ensure txindex will be triggered at least once

internal/testlog/testlog.go, log/logger.go
log: Add Handler getter to Logger interface
=> log: add Handler getter to Logger interface

accounts/abi/bind/base.go
accounts/abi: remove unused err set and check
=> accounts/abi/bind: remove unused err set and check

core/vm/contracts.go
=> core/vm: fix Prague contracts (#29612)

trie/trienode/node.go
trie: Preallocate capacity for fields slice
=> trie: preallocate capacity for fields slice

p2p/discover/v4_udp.go
=> remove unnecessary checks

common/math/big_test.go, common/math/integer.go
* chore: rename variable name `int` to `in`
* chore: rename variable name `int` to `n`
=> common/math: rename variable name `int` to `n`

core/state/access_list.go
rename all the receivers to 'al'
=> core/state: rename all the AccessList receivers to 'al'

accounts/abi/type.go, accounts/scwallet/wallet.go
* fix: Optimize regular initialization
* modify var name
* variable change to private types
=> accounts: avoid duplicate regex compilation

core/state/snapshot/snapshot.go
* upgrade lock usage
* revert unnecessary change
=> core/state/snapshot: add a missing lock

p2p/enr/enr_test.go, rlp/internal/rlpstruct/rlpstruct.go, rpc/handler.go, trie/secure_trie.go
make function comment match function name
=> chore: make function comment match function name

cmd/devp2p/discv4cmd.go, cmd/devp2p/discv5cmd.go, p2p/discover/table.go, p2p/discover/v4_udp.go, p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go
Here we add some API functions on the UDPv5 object for the purpose of implementing the Portal Network JSON-RPC API in the shisui client.
---------
=> p2p/discover: expose discv5 functions for portal JSON-RPC interface

crypto/signature_cgo.go, crypto/signature_nocgo.go
tinygo is having problems compiling the C implementation
=> crypto: use pure Go signature implementation in tinygo

core/vm/memory.go, miner/unconfirmed.go
remove redundant words in comment
=> chore: remove redundant words in comment
