CortexFoundation/CortexTheseus

- metrics/cpu.go
- metrics/cpu_syscall.go
- metrics/cpu_windows.go
- metrics/metrics.go
- params/fs.go
- torrentfs/storage.go
- torrentfs/types/merkle_tree_test.go
- torrentfs/types/types.go
For it will cost large compute to rebuild a mkt for file system to keep the state when the leaves number is too big. So we need to make a bandwidth for tree leaves to make sure the current root as the first leaf for next level tree. As above , we will only calculate mkt only using the leaves below the bandwidth and also keep the file system state.
This pr is under development for dev branch compare to add more features seriously.)
> New file system mkt level struct added, for high speed

- build/ci.go
- internal/build/azure.go
(cherry picked from commit fa01117498a580f8de35e026f7e0ab38313868dd)
> build/ci: handle split up listing

- core/tx_list.go
- core/tx_pool.go
- core/tx_pool_test.go
* core: added local tx pool test case
* core, crypto: various allocation savings regarding tx handling
* core/txlist, txpool: save a reheap operation, avoid some bigint allocs
Co-authored-by: Marius van der Wijden <m.vanderwijden@live.de>
(cherry picked from commit 6c9f040ebeafcc680b0c457e6f4886e2bca32527)
> core: transaction pool optimizations (#21328)

- console/bridge.go
- console/bridge_test.go
- internal/jsre/jsre.go
the otto still has problems in array sort
so try to use goja
> console,jsre: use goja instead of otto

- cmd/cortex/config.go
- cmd/cortex/cvm.go
- cmd/utils/flags.go
- core/state_transition.go
- core/vm/cvm.go
- core/vm/interpreter.go
- ctxc/handler.go
- go.mod
- go.sum
- inference/synapse/local_infer.go
- inference/synapse/synapse.go
- vendor/github.com/CortexFoundation/torrentfs/chaindb.go
- vendor/github.com/CortexFoundation/torrentfs/fs.go
- vendor/github.com/CortexFoundation/torrentfs/handler.go
- vendor/github.com/CortexFoundation/torrentfs/interfaces.go
- vendor/github.com/CortexFoundation/torrentfs/params/chain.go
- vendor/github.com/CortexFoundation/torrentfs/sync.go
- vendor/modules.txt
embedded storage to cortex full node and make the fast mode available
> Embedded-storage by using torrentfs

- cmd/cortex/cvm.go
- cmd/cortex/cvm_handler.go
- node/endpoints.go
- rpc/client.go
- rpc/http.go
- rpc/server.go
- rpc/testservice_test.go
- rpc/types.go
However,i don't get why if i return error last in a method,it will increse the nums the reciever.Types().Method()(including that method),which will cause getting more callbacks
> RPC:golint fix

- rlp/raw.go
- rlp/raw_test.go
This can be useful when working with raw RLP data. Rules around integers in RLP are too complicated to just use SplitString and decode the resulting byte slice.
> rlp: add SplitUint64 

- cmd/cortex/main.go
- core/rawdb/database.go
```
+-----------------+--------------------+------------+---------+
|    DATABASE     |      CATEGORY      |    SIZE    |  ITEMS  |
+-----------------+--------------------+------------+---------+
| Key-Value store | Headers            | 69.40 MiB  |   90020 |
| Key-Value store | Bodies             | 9.29 MiB   |   90020 |
| Key-Value store | Receipt lists      | 3.85 MiB   |   90020 |
| Key-Value store | Difficulties       | 4.12 MiB   |   90021 |
| Key-Value store | Block number->hash | 3.61 MiB   |   90002 |
| Key-Value store | Block hash->number | 93.94 MiB  | 2402617 |
| Key-Value store | Transaction index  | 41.36 MiB  | 1204867 |
| Key-Value store | Bloombit index     | 49.36 MiB  | 1200128 |
| Key-Value store | Contract codes     | 267.29 KiB |     107 |
| Key-Value store | Trie …
```
> inspect command enable and show details

- core/vm/gen_structlog.go
- core/vm/logger.go
* core/vm: marshall returnData as hexstring in trace logs
* core/vm: marshall returnData as hexstring in trace logs
> core/vm: marshall returnData as hexstring in trace logs

- core/state/sync_test.go
- p2p/enode/nodedb.go
- trie/sync_test.go
The database panicked for invalid IPs. This is usually no problem
because all code paths leading to node DB access verify the IP, but it's
dangerous because improper validation can turn this panic into a DoS
vulnerability. The quick fix here is to just turn database accesses
using invalid IP into a noop. This isn't great, but I'm planning to
remove the node DB for discv5 long-term, so it should be fine to have
this quick fix for half a year.
Fixes #21849
> p2p/enode: avoid crashing for invalid IP (#21981)

- p2p/dnsdisc/client.go
- p2p/dnsdisc/sync.go
In the random sync algorithm used by the DNS node iterator, we first pick a random
tree and then perform one sync action on that tree. This happens in a loop until any
node is found. If no trees contain any nodes, the iterator will enter a hot loop spinning
at 100% CPU.
The fix is complicated. The iterator now checks if a meaningful sync action can
be performed on any tree. If there is nothing to do, it waits for the next root record
recheck time to arrive and then tries again.
> p2p/dnsdisc: fix hot-spin when all trees are empty (#22313)

- p2p/dnsdisc/tree.go
This fixes the calculation of the tree branch factor. With the new
formula, we now creat at most 13 children instead of 30, ensuring
the TXT record size will be below 370 bytes.
> p2p/dnsdisc: fix flaw in dns size calculation 

- log/format.go
- log/format_test.go
* log: fix formatting of big.Int
The implementation of formatLogfmtBigInt had two issues: it crashed when
the number was actually large enough to hit the big integer case, and
modified the big.Int while formatting it.
* log: don't call FormatLogfmtInt64 for int16
* log: separate from decimals back, not front
Co-authored-by: Péter Szilágyi <peterke@gmail.com>
> log: fix formatting of big.Int

- trie/stacktrie.go
- trie/stacktrie_test.go
The stacktrie is a bit un-untuitive, API-wise: since it mutates input values.
Such behaviour is dangerous, and easy to get wrong if the calling code 'forgets' this quirk. The behaviour is fixed by this PR, so that the input values are not modified by the stacktrie.
Note: just as with the Trie, the stacktrie still references the live input objects, so it's still _not_ safe to mutate the values form the callsite.
> trie: make stacktrie not mutate input values

- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
When receiving PING from an IPv4 address over IPv6, the implementation sent
back a IPv4-in-IPv6 address. This change makes it reflect the IPv4 address.
> p2p/discover: improve discv5 handling of IPv4-in-IPv6 addresses

- p2p/rlpx/buffer.go
- p2p/rlpx/buffer_test.go
- p2p/rlpx/rlpx.go
- p2p/rlpx/rlpx_test.go
- p2p/transport.go
- rlp/raw.go
- rlp/raw_test.go
This change significantly improves the performance of RLPx message reads
and writes. In the previous implementation, reading and writing of
message frames performed multiple reads and writes on the underlying
network connection, and allocated a new []byte buffer for every read.
In the new implementation, reads and writes re-use buffers, and perform
much fewer system calls on the underlying connection. This doubles the
theoretically achievable throughput on a single connection, as shown by
the benchmark result:
name             old speed      new speed       delta
Throughput-8     70.3MB/s ± 0%  155.4MB/s ± 0%  +121.11%  (p=0.000 n=9+8)
The change also removes support for the legacy, pre-EIP-8 handshake encoding.
As of May 2021, no actively maintained client sends this format.
> p2p/rlpx: reduce allocation and syscalls 

- trie/trie.go
When deleting in fullNode, and the new child node nn is not nil, there is no need
to check the number of non-nil entries in the node. This is because the fullNode 
must've contained at least two children before deletion, so there must be another
child node other than nn.
> trie: small optimization of delete in fullNode case

- core/types/gen_log_json.go
- core/types/log.go
- core/types/receipt.go
- core/types/receipt_test.go
- core/vm/cvm.go
- core/vm/interpreter.go
The encoding of Log and LogForStorage is exactly the same
now. After tracking it down it seems like #17106 changed the
storage schema of logs to be the same as the consensus
encoding.
Support for the legacy format was dropped in #22852 and if
I'm not wrong there's no reason anymore to have these two
equivalent types.
Since the RLP encoding simply contains the first three fields
of Log, we can also avoid creating a temporary struct for
encoding/decoding, and use the rlp:"-" tag in Log instead.
Note: this is an API change in core/types. We decided it's OK
to make this change because LogForStorage is an implementation
detail of go-ethereum and the type has zero uses outside of
package core/types.
> core/types: remove LogForStorage type 

- core/rawdb/accessors_chain_test.go
* add db close to avoid goroutine leak
* core/rawdb: move close to defer
Co-authored-by: Martin Holst Swende <martin@swende.se>
> core/rawdb: close database in test to avoid goroutine leak

- core/vm/analysis.go
- core/vm/analysis_test.go
- core/vm/instructions.go
- core/vm/interpreter.go
* core/vm: more detailed benchmark for jumpdest analysis
* core/vm: make jd analysis benchmark alloc free
* core/vm: improve jumpdest analysis
* core/vm: improve worst-case
* core/vm: further improvements in analysis
* core/vm: improve jumpdest analysis >PUSH15
* core/vm: make jd analysis ref by value
* core/vm: fix misspell
* core/vm: improve set8 and set16 a bit
* core/vm: reduce amount of code
* core/vm: optimize byte copying
> core/vm: faster code analysis

- rlp/decode.go
- rlp/encode.go
- rlp/encode_test.go
- rlp/safe.go
- rlp/unsafe.go
As per benchmark results below, these changes speed up encoding/decoding of
consensus objects a bit.
name                             old time/op    new time/op    delta
EncodeRLP/legacy-header-8           384ns ± 1%     331ns ± 3%  -13.83%  (p=0.000 n=7+8)
EncodeRLP/london-header-8           411ns ± 1%     359ns ± 2%  -12.53%  (p=0.000 n=8+8)
EncodeRLP/receipt-for-storage-8     251ns ± 0%     239ns ± 0%   -4.97%  (p=0.000 n=8+8)
EncodeRLP/receipt-full-8            319ns ± 0%     300ns ± 0%   -5.89%  (p=0.000 n=8+7)
EncodeRLP/legacy-transaction-8      389ns ± 1%     387ns ± 1%     ~     (p=0.099 n=8+8)
EncodeRLP/access-transaction-8      607ns ± 0%     581ns ± 0%   -4.26%  (p=0.000 n=8+8)
EncodeRLP/1559-transaction-8        627ns ± 0%     606ns ± 1%   -3.44%  (p=0.000 n=8+8) …
> rlp: minor optimizations for slice/array encoding

- core/vm/analysis_test.go
* core/vm: rework jumpdest analysis benchmarks
For BenchmarkJumpdestOpAnalysis use fixed code size of ~1.2MB
and classic benchmark loop.
* core/vm: clear bitvec in jumpdest analysis benchmark
> core/vm: rework jumpdest analysis benchmarks

- p2p/discover/v5wire/encoding_test.go
- p2p/enode/localnode.go
- p2p/enode/nodedb.go
This PR ensures that wiping all data associated with a node (apart from its nodekey)
will not generate already used sequence number for the ENRs, since all remote nodes
would reject them until they out-number the previously published largest one.
The big complication with this scheme is that every local update to the ENR can
potentially bump the sequence number by one. In order to ensure that local updates
do not outrun the clock, the sequence number is a millisecond-precision timestamp,
and updates are throttled to occur at most once per millisecond.
> p2p/enode: use unix timestamp as base ENR sequence number

- rpc/websocket.go
- rpc/websocket_test.go
This PR adds a 30s timeout for the remote part to answer a ping message, thus detecting (silent) disconnnects
> rpc: set pong read deadline

- core/blockchain.go
- core/blockchain_insert.go
It is because write known block only checks block and state without snapshot, which could lead to gap between newest snapshot and newest block state. However, new blocks which would cause snapshot to become fixed were ignored, since state was already known.
> core: fix snapshot missing when recovery from crash

- core/tx_noncer.go
- core/tx_pool.go
- core/tx_pool_test.go
* Adjust pending nonce update operation
Benchmark the speed of transaction insertion under multiple accounts
core: fix rebase issues + docstring
core: make benchmark test use sync:ed method
* core: address review comments
* core: add memreport to benchmark
> core: more efficient nonce-update in txpool

- consensus/clique/clique.go
- miner/worker.go
This PR fixes a problem which arises on clique networks when there is a network stall. Previously, the worker packages were tracked, even if the sealing engine decided not to seal the block (due to clique rules about recent signing). These tracked-but-not-sealed blocks kept building up in memory.
This PR changes the situation so the sealing engine instead returns an error, and the worker can thus un-track the package.
> miner, consensus/clique: avoid memory leak during block stasis

- core/rawdb/chain_iterator.go
* core/rawdb: utilize AncientRange when initiating from freezer
* core/rawdb: remove debug sanity check
> core/rawdb: use AncientRange when initializing leveldb from freezer

- trie/stacktrie.go
Trim the search key from head as it's being pushed deeper into the trie. Previously the search key was never modified but each node kept information how to slice and compare it in keyOffset. Now the keyOffset is not needed as this information is included in the slice of the search key. This way the keyOffset can be removed and key manipulation
simplified.
> trie: simplify StackTrie implementation

- core/blockchain.go
- core/rawdb/chain_iterator.go
This PR fixes a special corner case in transaction indexing.
When the chain is rewound by SetHead to a historical point which is even lower than the transaction indexes tail, then system will report Failed to decode block body error all the time, because the relevant blocks are already deleted.
In order to avoid this "non-critical-but-annoying" issue, we can recap the indexing target to head+1(to is excluded, so it means indexing transactions from 0 to head).
> core, core/rawdb: fix transaction indexing

- core/asm/lexer.go
This orders the items in slice definition same as the enum values.
> core/asm: change order of items in stringtokenTypes

- crypto/ecies/ecies_test.go
- crypto/ecies/params.go
Using curve P384 for encryption causes the error "ecies: shared key params
are too big". Also, readme.md says curve P384 should use AES192 not AES256.
> crypto/ecies: use AES-192 for curve P384 

- p2p/peer.go
- p2p/peer_error.go
All other implementations store disconnect reasons as a single byte,
so go-ethereum should do it too.
> p2p: define DiscReason as uint8

- rlp/encbuffer.go
- rlp/encode.go
- rlp/encode_test.go
- trie/committer.go
- trie/database.go
- trie/hasher.go
- trie/iterator.go
- trie/node.go
- trie/node_enc.go
- trie/proof.go
- trie/stacktrie.go
- trie/trie_test.go
This change speeds up trie hashing and all other activities that require
RLP encoding of trie nodes by approximately 20%. The speedup is achieved by
avoiding reflection overhead during node encoding.
The interface type trie.node now contains a method 'encode' that works with
rlp.EncoderBuffer. Management of EncoderBuffers is left to calling code.
trie.hasher, which is pooled to avoid allocations, now maintains an
EncoderBuffer. This means memory resources related to trie node encoding
are tied to the hasher pool.
> rlp, trie: faster trie node encoding

- trie/iterator.go
- trie/iterator_test.go
* trie: fix memory leak in trie iterator
In the trie iterator, live nodes are tracked in a stack while iterating.
Popped node states should be explictly set to nil in order to get
garbage-collected.
* trie: fix empty trie iterator
> trie: fix two issues in trie iterator 

- p2p/peer_error.go
It was 'int' accidentally, should be DiscReason instead.
> p2p: fix type of DiscSubprotocolError 

- core/rawdb/accessors_chain.go
- core/rawdb/chain_freezer.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/freezer_batch.go
- core/rawdb/freezer_test.go
- core/rawdb/table.go
- ctxcdb/database.go
Previously freezer has only been used for storing ancient chain data, while obviously it can be used more. This PR unties the chain data and freezer, keep the minimal freezer structure and move all other logic (like incrementally freezing block data) into a separate structure called ChainFreezer.
This PR also extends the database interface by adding a new ancient store function AncientDatadir which can return the root directory of ancient store. The ancient root directory can be used when we want to open some other ancient-stores (e.g. reverse diff freezer).
> core/rawdb: untie freezer and ancient chain data

- trie/database.go
Decrease children size instead of dirties size when marking dirties as cleaned up in trie cleaner
> trie: fix size accounting in cleaner

- core/blockchain.go
* Remove locking in (*BlockChain).ExportN
Since ExportN is read-only, it shouldn't need the lock. (?)
* Add hash check to detect reorgs during export.
* fix check order
* Update blockchain.go
* Update blockchain.go
Co-authored-by: rjl493456442 <garyrong0905@gmail.com>
> core: remove lock in BlockChain.ExportN

- rlp/rlpgen/main.go
typ will be nil when lookupStructType returns an error. cfg.Type should be used instead.
> rlp/rlpgen: fix error handling when target type not found

- trie/database.go
- trie/node.go
- trie/node_test.go
This avoids copying the input []byte while decoding trie nodes. In most
cases, particularly when the input slice is provided by the underlying
database, this optimization is safe to use.
For cases where the origin of the input slice is unclear, the copying version
is retained. The new code performs better even when the input must be
copied, because it is now only copied once in decodeNode.
> trie: improve node rlp decoding performance

- core/blockchain.go
- core/rawdb/ancient_scheme.go
This PR makes the event-sending for deleted and new logs happen in batches, to prevent OOM situation due to large reorgs.
> core: place a cap on reorglogs 

- rpc/server.go
rpc: fix connection tracking in Server
When upgrading to mapset/v2 with generics, the set element type used in rpc.Server had to be changed to *ServerCodec because ServerCodec is not 'comparable'. While the distinction is technically correct, we know all possible ServerCodec types, and all of them are comparable. So just use a map instead.
> rpc: fix connection tracking set in Server

- core/rawdb/freezer.go
* core/rawdb: fix freezer validation
* core/rawdb: address comment
> core/rawdb: fix freezer validation

- rpc/websocket.go
This is to cater for more node providers.
> rpc: decrease websocket ping interval

- core/txpool/list.go
- core/types/transaction.go
- p2p/util.go
This changes the Pop method to assign the zero value before reducing slice size. Doing so ensures the backing array does not reference removed item values.
> all: assign zero after resize in implementations of heap.Interface 

- p2p/nat/natpmp.go
> p2p/nat: handle responses with alternative port in NAT-PMP 

- build/ci.go
Adds uploads to Kinetic in Launchpad, and removes the upload for 21.10 impish (not supported since July)
> build: add support for Ubuntu 22.10 (Kinetic Kudu) 

- core/rawdb/chain_freezer.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_test.go
- go.mod
- go.sum
- vendor/github.com/CortexFoundation/torrentfs/Makefile
- vendor/github.com/CortexFoundation/torrentfs/backend/handler.go
- vendor/modules.txt
This PR fixes an issue which might result in data lost in freezer.
Whenever mutation happens in freezer, all data will be written into head data file and it will be rotated with a new one in case the size of file reaches the threshold.
Theoretically, the rotated old data file should be fsync'd to prevent data loss. In freezer.Sync function, we only fsync: (1) index file (2) meta file and (3) head data file. So this PR forcibly fsync the head data file if mutation happens in the boundary of data file.
> core/rawdb: fsync head data file before closing it

- core/rawdb/chain_freezer.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_test.go
This PR does a few things.
It fixes a shutdown-order flaw in the chainfreezer. Previously, the chain-freezer would shutdown the freezer backend first, and then signal for the loop to exit. This can lead to a scenario where the freezer tries to fsync closed files, which is an error-conditon that could lead to exit via log.Crit.
It also makes the printout more detailed when truncating 'dangling' items, by showing the exact number instead of approximate MB.
This PR also adds calls to fsync files before closing them, and also makes the `db inspect` command slightly more robust.
> core/rawdb: fix cornercase shutdown behaviour in freezer

- core/chain_makers.go
Since forks are now scheduled by block time, it can be necessary to check the timestamp of a block while generating transactions.
> core: add Timestamp method in BlockGen (#26844)

- p2p/discover/v5_udp.go
- p2p/discover/v5wire/encoding.go
This makes it possible to run another protocol alongside discv5, by reading  unhandled packets from the channel.
> p2p/discover: pass invalid discv5 packets to Unhandled channel

- rlp/decode.go
- rlp/decode_test.go
- rlp/encbuffer.go
- rlp/encode.go
- rlp/encode_test.go
- rlp/rlpgen/gen.go
- rlp/rlpgen/gen_test.go
- rlp/rlpgen/testdata/uint256.in.txt
- rlp/rlpgen/testdata/uint256.out.txt
- rlp/rlpgen/types.go
This adds built-in support in package rlp for encoding, decoding and generating code dealing with uint256.Int.
---------
> rlp: support for uint256

- core/txpool/txpool.go
Local transactions should not be subject to the "future shouldn't churn pending txs" rule
> core/txpool: allow future local transactions

- core/txpool/list.go
- core/txpool/txpool.go
- core/txpool/txpool2_test.go
- core/txpool/txpool_test.go
Makes use of atomic.Uint64 instead of atomic by pointer
> core/txpool: use atomic int added in go1.19 

- accounts/abi/bind/base.go
- accounts/abi/bind/base_test.go
- consensus/cuckoo/consensus_test.go
Adds error handling for the case that UnpackLog or UnpackLogIntoMap is called with a log that has zero topics.
---------
> accounts/abi/bind: handle UnpackLog with zero topics

- core/txpool/txpool.go
- core/txpool/txpool_test.go
Currently, most of transaction validation while holding the txpool mutex: one exception being an early-on signature check.
This PR changes that, so that we do all non-stateful checks before we entering the mutex area. This means they can be performed in parallel, and to enable that, certain fields have been made atomic bools and uint64.
> core/txpool: move some validation to outside of mutex

- core/txpool/list.go
- core/txpool/txpool.go
- core/txpool/txpool2_test.go
Prior to this change, it was possible that transactions are erroneously deemed as 'future' although they are in fact 'pending', causing them to be dropped due to 'future' not being allowed to replace 'pending'.
This change fixes that, by doing a more in-depth inspection of the queue.
> core/txpool: disallow future churn by remote txs

- cmd/devp2p/crawl.go
cmd/devp2p: fix log of ignored recent nodes counter
> cmd/devp2p: fix erroneous log output in crawler

- log/format.go
* log/format.go : invalid string cast fix
* log: some polish
---------
> log: report error when ctx key is non-string

- cmd/utils/cmd.go
When block import fails, the error displays the number of the first block past the import batch, not the number of the failing block. This change fixes this problem by identifying which blocks fails and reporting its number.
> cmd/utils: report the blocknumber when block import fails

- go.mod
- go.sum
- p2p/discover/common.go
- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v5_udp.go
- vendor/github.com/dgraph-io/badger/v4/db.go
- vendor/modules.txt
* p2p/discover: remove ReadRandomNodes
Even though it's public, this method is not callable by code outside of package p2p/discover because one can't get a valid instance of Table.
* p2p/discover: add Table.Nodes
* p2p/discover: make Table settings configurable
In unit tests and externally developed cmd/devp2p test runs, it can be useful to tune the timer intervals used by Table.
> p2p/discover: add Table configuration and Nodes method

- core/state/journal.go
- core/state/statedb.go
This changes the journal logic to mark the state object dirty immediately when it is reset. 
We're mostly adding this change to appease the fuzzer. Marking it dirty immediately makes no difference in practice because accounts will always be modified by CVM right after creation.
> core/state: mark account as dirty when resetObject occurs

- rpc/client.go
- rpc/errors.go
- rpc/json.go
- rpc/subscription.go
This adds two ways to check for subscription support. First, one can now check whether the transport method (HTTP/WS/etc.) is capable of subscriptions using the new Client.SupportsSubscriptions method.
Second, the error returned by Subscribe can now reliably be tested using this pattern:
sub, err := client.Subscribe(...)
if errors.Is(err, rpc.ErrNotificationsUnsupported) {
// no subscription support
}
---------
> rpc: add method to test for subscription support

- p2p/discover/v4_udp.go
In all other UDPv4 methods, the deadline is checked first. It seems weird to me that ping is an exception. Deadline comparison is also less resource intensive.
> p2p/discover: swap verification order in discv4 ping handler

- core/rawdb/freezer.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_table_test.go
- core/rawdb/freezer_utils.go
This change adds the ability to perform reads from freezer without size limitation. This can be useful in cases where callers are certain that out-of-memory will not happen (e.g. reading only a few elements).
The previous API was designed to behave both optimally and secure while servicing a request from a peer, whereas this change should _not_ be used when an untrusted peer can influence the query size.
> core/rawdb: support freezer batch read with no size limit 

- crypto/kzg4844/kzg4844.go
- crypto/kzg4844/kzg4844_ckzg_cgo.go
- crypto/kzg4844/kzg4844_test.go
* crypto/kzg4844: remove unnecessary init call & fix typo
* Fix kzg4844 tests/benchmarks
* Make init lazy & revert changes to tests
> crypto/kzg4844: do lazy init in all ckzg funcs

- core/rawdb/accessors_metadata.go
This changes removes the warn-printout about not finding unclean shutdown markers, which always happens on fresh installs / wiped databases.
> core/rawdb: don't warn for missing "unclean shutdown markers"

- common/types.go
- common/types_test.go
- log/format.go
- log/handler_glog.go
- log/logger.go
- log/logger_test.go
Avoids the somewhat expensive stack.Caller invocation by checking if it is needed
> log: avoid stack lookups when not needed/used

- cmd/devp2p/crawl.go
- cmd/devp2p/discv4cmd.go
- cmd/devp2p/discv5cmd.go
This PR makes the tool use the --bootnodes list as the input to devp2p crawl. The flag will take effect if the input/output.json file is missing or empty.
> cmd/devp2p: use bootnodes as crawl input

- core/rawdb/freezer_table.go
Avoid truncating files, if ancients are opened in readonly mode. With this change, we return error instead of trying (and failing)  to repair
> core/rawdb: no need to run truncateFile for readonly mode

- core/rawdb/freezer.go
- core/rawdb/freezer_test.go
This allows using the freezer from multiple processes at once in read-only mode.
> core/rawdb: use readonly file lock in readonly mode

- core/state/trie_prefetcher.go
> core/state: small trie prefetcher nits 

- build/ci.go
- core/blockchain.go
- core/state/snapshot/disklayer.go
- core/state/snapshot/snapshot.go
This change fixes a memory leak, when running either state-tests or blockchain-tests, we allocate a `1MB` fastcache during snapshot generation. `fastcache` is a bit special, and requires a `Reset()` (it has it's own memory allocator).
> core/state, tests: fix memory leak via fastcache

- core/rawdb/freezer_resettable.go
- core/rawdb/freezer_table.go
- crypto/kzg4844/kzg4844_ckzg_cgo.go
This PR adds more error message for debugging purpose.
> trie/triedb/pathdb, core/rawdb: enhance error message in freezer

- core/asm/asm_test.go
- core/vm/opcodes.go
Fixes so that `push0` opcode is correctly reported as `true` by the `IsPush` function
---------
> fix isPush for push0

- accounts/abi/method.go
refactor: improve readability of NewMethod print
> accounts/abi: improve readability of method-to-string conversion

- accounts/abi/error.go
adds contextual information to errors returned by unpack
> accounts/abi: context info on unpack-errors

- accounts/keystore/account_cache.go
- accounts/keystore/account_cache_test.go
- core/state/statedb_test.go
- rpc/client_test.go
* rpc: make subscription test faster
reduces time for TestClientSubscriptionChannelClose from 25 sec to < 1 sec.
* trie: cache trie nodes for faster sanity check
This reduces the time spent on TestIncompleteSyncHash from ~25s to ~16s.
* core/forkid: speed up validation test
This takes the validation test from > 5s to sub 1 sec
* core/state: improve snapshot test run brings the time for TestSnapshotRandom from 13s down to 6s
* accounts/keystore: improve keyfile test
This removes some unnecessary waits and reduces the runtime of TestUpdatedKeyfileContents from 5 to 3 seconds
* trie: remove resolver
* trie: only check ~5% of all trie nodes
> core, trie, rpc: speed up tests

- internal/testlog/testlog.go
- log/format.go
- log/format_test.go
- log/handler.go
- log/logger_test.go
These changes improves the performance of the non-coloured terminal formatting, _quite a lot_. 
```
name               old time/op    new time/op    delta
TerminalHandler-8    10.2µs ±15%     5.4µs ± 9%  -47.02%  (p=0.008 n=5+5)
name               old alloc/op   new alloc/op   delta
TerminalHandler-8    2.17kB ± 0%    0.40kB ± 0%  -81.46%  (p=0.008 n=5+5)
name               old allocs/op  new allocs/op  delta
TerminalHandler-8      33.0 ± 0%       5.0 ± 0%  -84.85%  (p=0.008 n=5+5)
```
I tried to _somewhat_ organize the commits, but the it might still be a bit chaotic. Some core insights: 
- The function `terminalHandler.Handl` uses a mutex, and writes all output immediately to 'upstream'. Thus, it can reuse a scratch-buffer every time. 
- This buffer can be propagated internally, making …
> slog: faster and less memory-consumption

- log/root.go
slog.SetDefault has undesirable side effects. It also sets the default logger destination, for example. So we should not call it by default in init.
> log: avoid setting default slog logger in init

- core/blockchain.go
This pull request resets the txlookup cache if chain reorg happens, preventing them from remaining reachable. It addresses failures in the hive tests.
> core: reset tx lookup cache if necessary 

- core/rawdb/chain_freezer.go
- core/rawdb/database.go
* core: use finalized block as the chain freeze indicator
* core/rawdb: use max(finality, head-90k) as chain freezing threshold
* core/rawdb: fix tests
* core/rawdb: fix lint
* core/rawdb: address comments from peter
* core/rawdb: fix typo
> core: use finalized block as the chain freeze indicator

- common/math/big.go
common/math: does not change base parameter
> common/math: copy result in Exp

- core/state/access_list.go
- core/state/state_object.go
- core/state/statedb.go
> core/state: use maps.Clone

- rlp/decode.go
- rlp/encode.go
reflect.PtrTo has been deprecated and superseded by reflect.PointerTo
> rlp: replace reflect.PtrTo with reflect.PointerTo

- core/vm/contracts.go
core: make bls precompiled contract use the correct address as in eip
> core/vm: move bls precompiles to correct addresses

- core/vm/instructions.go
- ctxc/downloader/downloader_test.go
* optimize-push
* revert push1 change
* Update instructions.go
* core/vm: go format
* core/vm: fix nit
---------
> core/vm: refactor push-functions to use `min` builtin

- core/state/journal.go
- core/state/state_object.go
Currently our state journal tracks each storage update to a contract, having the ability to revert those changes to the previously set value.
For the very first modification however, it behaves a bit wonky. Reverting the update doesn't actually remove the dirty-ness of the slot, rather leaves it as "change this slot to it's original value". This can cause issues down the line with for example write witnesses needing to gather an unneeded proof.
This PR modifies the storageChange journal entry to not only track the previous value of a slot, but also whether there was any previous value at all set in the current execution context. In essence, the PR changes the semantic of storageChange so it does not simply track storage changes, rather it tracks dirty storage changes, an important …
> core/state: storage journal entry should revert dirtyness too

- core/state/access_list.go
- core/state/state_object.go
- core/state/statedb_test.go
- core/state/transient_storage.go
This PR fixes some flaws with the existing tests.
The randomized testing (TestSnapshotRandom) executes a series of steps which modify the state and create journal-events. Later on, we compare the forward-going-states against the backwards-unrolling-journal-states, and check that they are identical.
The "identical" check is performed using various accessors. It turned out that we failed to check some things:
- the accesslist contents
- the transient storage contents
- the 'newContract' flag
- the dirty storage map
This change adds these new checks
> core/state: better randomized testing (postcheck) on journalling

- accounts/keystore/keystore.go
- accounts/scwallet/hub.go
- core/mkalloc.go
* fix: open file used up but not closed
* feat: more same case
* feat: accept conversation
> close opened files

- cmd/devp2p/discv4cmd.go
- internal/testlog/testlog.go
- node/api.go
- p2p/discover/common.go
- p2p/discover/lookup.go
- p2p/discover/node.go
- p2p/discover/table.go
- p2p/discover/table_reval.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v4_udp_test.go
- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/server.go
Node discovery periodically revalidates the nodes in its table by sending PING, checking if they are still alive. I recently noticed some issues with the implementation of this process, which can cause strange results such as nodes dropping unexpectedly, certain nodes not getting revalidated often enough, and bad results being returned to incoming FINDNODE queries.
In this change, the revalidation process is improved with the following logic:
- We maintain two 'revalidation lists' containing the table nodes, named 'fast' and 'slow'.
- The process chooses random nodes from each list on a randomized interval, the interval being faster for the 'fast' list, and performs revalidation for the chosen node.
- Whenever a node is newly inserted into the table, it goes into the 'fast' list. Once …
> p2p/discover: improved node revalidation

- p2p/enode/idscheme.go
- p2p/enode/node.go
- p2p/enode/node_test.go
- p2p/enode/nodedb.go
- p2p/enode/urlv4.go
- p2p/enr/entries.go
enode.Node has separate accessor functions for getting the IP, UDP port and TCP port. These methods performed separate checks for attributes set in the ENR.
With this PR, the accessor methods will now return cached information, and the endpoint is determined when the node is created. The logic to determine the preferred endpoint is now more correct, and considers how 'global' each address is when both IPv4 and IPv6 addresses are present in the ENR.
> p2p/enode: fix endpoint determination for IPv6

- core/state/statedb.go
Always prefetch the account trie while starting the prefetcher.
> core/state: prefetch account trie while starting a prefetcher

- cmd/devp2p/internal/v4test/framework.go
- cmd/devp2p/nodesetcmd.go
- cmd/devp2p/rlpxcmd.go
- p2p/dial.go
- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v4_udp_test.go
- p2p/discover/v5_udp.go
- p2p/discover/v5wire/encoding_test.go
- p2p/enode/localnode.go
- p2p/enode/localnode_test.go
- p2p/enode/nodedb.go
- p2p/enode/nodedb_test.go
- p2p/netutil/addrutil.go
- p2p/netutil/iptrack.go
- p2p/netutil/iptrack_test.go
- p2p/netutil/net.go
- p2p/netutil/net_test.go
- p2p/server.go
- p2p/server_nat_test.go
enode.Node was recently changed to store a cache of endpoint information. The IP address in the cache is a netip.Addr. I chose that type over net.IP because it is just better. netip.Addr is meant to be used as a value type. Copying it does not allocate, it can be compared with ==, and can be used as a map key.
This PR changes most uses of Node.IP() into Node.IPAddr(), which returns the cached value directly without allocating. While there are still some public APIs left where net.IP is used, I have converted all code used internally by p2p/discover to the new types. So this does change some public Go API, but hopefully not APIs any external code actually uses.
There weren't supposed to be any semantic differences resulting from this refactoring, however it does introduce one: In package …
> p2p: use netip.Addr where possible

- rlp/raw.go
rlp: no need to repeat calling len
> rlp: no need to repeat called len method

- core/state/snapshot/snapshot.go
* core/state/snapshot: acquire the lock on release
* core/state/snapshot: only acquire read-lock when iterating
> core/state/snapshot: acquire the lock on Release

- common/types.go
- common/types_test.go
Since Decimal is defined as unsiged `uint64`, we should use `strconv.ParseUint` instead of `strconv.ParseInt` during unmarshalling.
---------
> common: using `ParseUint` instead of `ParseInt` 

- core/state/statedb.go
This pull request fixes the broken feature where the entire storage set is overridden.
Originally, the storage set override was achieved by marking the associated account as deleted, preventing access to the storage slot on disk. However, since #29520, this flag is also checked when accessing the account, rendering the account unreachable.
A fix has been applied in this pull request, which re-creates a new state object with all account metadata inherited.
> core/state: fix SetStorage override behavior

- p2p/nat/nat.go
Return the actually requested external port instead of 0 in the AddMapping implementation for `--nat extip:<IP>`.
> p2p/nat: return correct port for ExtIP NAT

- p2p/server_nat_test.go
The test specifies `ListenAddr: ":0"`, which means a random ephemeral port will be chosen for the TCP listener by the OS. Additionally, since no `DiscAddr` was specified, the same port that is chosen automatically by the OS will also be used for the UDP listener in the discovery UDP setup. This sometimes leads to test failures if the TCP listener picks a free TCP port that is already taken for UDP. By specifying `DiscAddr: ":0"`, the UDP port will be chosen independently from the TCP port, fixing the random failure.
Verified using
```
cd p2p
go test -c -race
stress ./p2p.test -test.run=TestServerPortMapping
...
5m0s: 4556 runs so far, 0 failures
```
The issue described above can technically lead to sporadic failures on systems that specify a listen address via the `--port` flag of 0 while …
> p2p: fix flaky test TestServerPortMapping 

- internal/build/env.go
When we are building in detached head, we cannot easily obtain the same information as we can if we're in non-detached head.
However, one thing we _can_ obtain is the git-hash and git-date. Currently, we omit to include the git-date into the build-info, which causes problem for reproducable builds which are on a detached head.
This change fixes it to include the date-info always.
> internal/build: include git-date on detached head

- p2p/discover/metrics.go
`WriteToUDP` was never called, since `meteredUdpConn` exposed directly all the methods from the underlying `UDPConn` interface.
This fixes the `discover/egress` metric never being updated.
> p2p/discover: fix Write method in metered connection 

- core/types/block.go
The existing implementation is correct when building and verifying blocks, since we will only collect non-empty requests into the block requests list.
But it isn't correct for cases where a requests list containing empty items is sent by the consensus layer on the engine API. We want to ensure that empty requests do not cause a difference in validation there, so the commitment computation should explicitly skip them.
> core/types: add length check in CalcRequestsHash

- build/ci.go
Travis often fails because the test times out.
> build: bump test timeout

- build/ci.go
This changes the `-upload` flag to just toggle the upload. The remote image name is now configured using the `-hub` flag.
> build: provide a flag to disable publishing in dockerx build

- accounts/abi/argument.go
- accounts/abi/unpack_test.go
Slightly improves performance of abi.Unpack
```
Before
BenchmarkUnpack/0-14   5965714       210.9 ns/op     280 B/op       5 allocs/op
BenchmarkUnpack/1-14   2148283       569.7 ns/op     688 B/op      16 allocs/op
After:
BenchmarkUnpack/0-14  	 7693365	       151.2 ns/op	     136 B/op	       4 allocs/op
BenchmarkUnpack/1-14  	 2261294	       508.9 ns/op	     544 B/op	      15 allocs/op
```
---------
> accounts/abi: improve unpack performance 

- log/root.go
- log/root_test.go
Currently, even though it takes in a `Logger` interface, `log.SetDefualt` enforces that the concrete type of the provided logger is `*logger` because:
1. in `init` `root.Store` is called with a `*logger`
2. `atomic.Value` panics if the concrete type provided in `Store` is not consistent across calls.
([ref](https://pkg.go.dev/sync/atomic#Value.Store))
> All calls to Store for a given Value must use values of the same
concrete type.
This PR changes to use `sync.RWMutex` and adds a test that panics on `master`.
> log: fix SetDefault for custom loggers

- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/discover/v5wire/encoding.go
This fixes the handshake in a scenario where the remote end sends two unknown packets in a row. When this happens, we would previously respond to both with a WHOAREYOU challenge, but keep only the latest sent challenge. Transmission is assumed to be unreliable, so any client that sends two request packets simultaneously has to be prepared to follow up on whichever request leads to a handshake. With this fix, we force them to do the handshake that we can actually complete.
> p2p/discover: repeat WHOAREYOU challenge when handshake in progress

- p2p/nat/natupnp.go
It introduces a new variable to store the external port returned by the addAnyPortMapping function and ensures that the correct external port is returned even in case of an error.
> p2p/nat: improve AddMapping code

- p2p/discover/v5_udp_test.go
- p2p/discover/v5wire/encoding.go
- p2p/discover/v5wire/msg.go
When resending the WHOAREYOU packet, a new nonce and random IV should not be generated. The sent packet needs to match the previously-sent one exactly in order to make the handshake retry work.
---------
> p2p/discover: repeat exact encoding when resending WHOAREYOU packet 

- p2p/discover/v5_talk.go
- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/discover/v5wire/encoding.go
- p2p/discover/v5wire/encoding_test.go
- p2p/discover/v5wire/session.go
This is for the implementation of Portal Network in the Shisui client. Their handler needs access to the node object in order to send further calls to the requesting node. This is a breaking API change but it should be fine, since there are basically no known users of TALKREQ outside of Portal network.
---------
> p2p/discover: pass node instead of node ID to TALKREQ handler

- cmd/devp2p/internal/v5test/discv5tests.go
This adds the test description text to the output, instead of keeping it as a Go comment. Logs are visible in the hive UI where these tests run, while Go comments are not.
> cmd/devp2p/internal/v5test: log test descriptions

- p2p/metrics.go
- p2p/peer.go
Our previous success metrics gave success even if a peer disconnected right after connection. These metrics only count peers that stayed connected for at least 1 min. The 1 min limit is an arbitrary choice. We do not use this for decision logic, only statistics.
> p2p: better dial/serve success metrics

- core/filtermaps/chain_view.go
This PR makes `filtermaps.ChainView` thread safe because it is used concurrently both by the indexer and multiple matcher threads. Even though it represents an immutable view of the chain, adding a mutex lock to the `blockHash` function is necessary because it does so by extending its list of non-canonical hashes if the underlying blockchain is changed.
The unsafe concurrency did cause a panic once after running the unit tests for several hours and it could also happen during live operation.
> core/filtermaps: make ChainView thread safe

- core/state/journal.go
Missing field origvalue when copying storageChange.
> core/state: fix copy of storageChange

- core/state/statedb.go
Improvement: preallocate capacity for `logs` at first to avoid reallocating multi times.
> core/state: preallocate capacity for logs list
